import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'prefferedLanguage': 'select your Preffered language',
          'sameLanguage': 'You will use the same Language for the entire App',
          'Next': 'Next',
          'continue': 'Continue',
          'ecofriendlyandbiodegradable': 'Eco Friendly and Bio-degradable',
          'letssignin': 'Let\'s Sign in',
          'email': 'Email',
          'password': 'Password',
          'signin': 'Sign in',
          'donthaveanaccount': 'Don\'t have an account?',
          'signup': 'Sign up',
          'letssignup': 'Let\'s Sign uo',
          'createaccount': 'Create Account',
          'alreadyhaveanaccount': 'Already have an account?',
          'addnewitem': 'Add new Items',
          'save': 'Save',
          'notifications': 'Notifications',
          'myorders': 'My orders',
          'settings': 'Settings',
          'home': 'Home',
          'earnings': 'Earnings',
          'personalbalance': 'Personal Balance',
          'earninginjune': 'Earning in june',
          'totalorders': 'Total Orders',
          'activeorders': 'Active orders',
          'myitems': 'My Items',
          'nonotifications': 'No Notifications',
          'orders': 'Orders',
          'noorders': 'No Orders',
          'profile': 'Profile',
          'accountbalance': 'Account Balance',
          'privacypolicy': 'Privacy & Policy',
          'help': 'Help',
          'aboutapp': 'About App',
          'logout': 'Logout',
          'update': 'Update',
          'darkmode': 'Dark Mode',
          'seeAll': 'See All',
          'withdraw': 'With Draw',
          'withdrawalmethods': 'Withdrawal Methods',
          'payoneer': 'Payoneer',
          'paypal': 'PayPal',
          'completed': 'Completed',
          'cancelled': 'Cancelled',
          'returned': 'Returned'

          // 'enterpassword': 'Enter Password',
          // 'retypePassword': 'Re-type Password',
          // 'about': 'About',
          // 'alreadyHaveacc': 'Already have an account?',
          // 'login': 'Login',
          // 'or': 'OR',
          // 'yournewPass':
          //     'Your New password must be different from your previous password',
          // 'newpassword': 'New Password',
          // 'retypePass': 'Re-type Password',
          // 'reviewyourorder': 'Review your order',
          // 'thanksforyourorder': 'Thanks for your order',
          // 'trackorder': 'Track order',
          // 'ordersummary': 'Order Summary',
          // 'ordernumber': 'Order Number',
          // 'amountpaid': 'Amount Paid',
          // 'addresses': 'Addresses',
          // 'addnewaddress': 'Add New Address',
          // 'newaddress': 'New Address',
          // 'usemycurrentlocation': 'Use my current location',
          // 'typeaddresstitle': 'Type address Title',
          // 'country': 'Country',
          // 'city': 'City',
          // 'town': 'Town',
          // 'street': 'Street',
          // 'housenumber': 'House Number',
          // 'phoneNumber': 'Phone Number',
          // 'setdefaultAddress': 'Set Default Address',
          // 'saveaddress': 'Save Address',
        },
        'es_ES': {
          'prefferedLanguage': 'seleccione su idioma preferido',
          'sameLanguage': 'Usarás el mismo idioma para toda la aplicación',
          'Next': 'Próxima',
          'continue': 'Continuar',
          'ecofriendlyandbiodegradable':
              'Respetuosa del medio ambiente y biodegradable',
          'letssignin': 'Vamos a iniciar sesión',
          'email': 'Correo electrónico',
          'password': 'Contraseña',
          'signin': 'Iniciar sesión',
          'donthaveanaccount': 'No tienes una cuenta?',
          'signup': 'Inscribirse',
          'letssignup': 'Registrémonos',
          'createaccount': 'Crear una cuenta',
          'alreadyhaveanaccount': 'Ya tienes una cuenta?',
          'addnewitem': 'Agregar nuevos elementos',
          'save': 'Ahorrar',
          'notifications': 'Notificaciones',
          'myorders': 'Mis ordenes',
          'settings': 'Ajustes',
          'home': 'Hogar',
          'earnings': 'Ganancias',
          'personalbalance': 'Saldo personal',
          'earninginjune': 'ganando en junio',
          'totalorders': 'Pedidos totales',
          'activeorders': 'Pedidos activos',
          'myitems': 'Mis cosas',
          'nonotifications': 'No Notificaciones',
          'orders': 'Pedidos',
          'noorders': 'Sin pedidos',
          'profile': 'Perfil',
          'accountbalance': 'Saldo de la cuenta',
          'privacypolicy': 'Política de privacidad',
          'help': 'Ayuda',
          'aboutapp': 'Acerca de la aplicación',
          'logout': 'Cerrar sesión',
          'update': 'Actualizar',
          'darkmode': 'Modo oscuro',
          'seeAll': 'See All',
          'withdraw': 'Retirar',
          'withdrawalmethods': 'Métodos de retiro',
          'payoneer': 'Payoneer',
          'paypal': 'Paypal',
          // 'completed': 'Completed',
          // 'cancelled': 'Cancelled',
          // 'returned': 'Returned'
        },
      };
}
